version: '3'
services:
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx/conf.d:/etc/nginx/conf.d
      - nginx/vhost.d:/etc/nginx/vhost.d
      - nginx/html:/usr/share/nginx/html
      - nginx/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - nginx/conf.d:/etc/nginx/conf.d
      - nginx/vhost.d:/etc/nginx/vhost.d
      - nginx/html:/usr/share/nginx/html
      - nginx/certs:/etc/nginx/certs:ro
      - nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - nginx/conf.d:/etc/nginx/conf.d
      - nginx/vhost.d:/etc/nginx/vhost.d
      - nginx/html:/usr/share/nginx/html
      - nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  web:
    build: .
    command: bash -c "./wait-for-it.sh neo4j:7474 -- bundle exec rails s"
    volumes:
      - ./app:/app
    links:
      - postgres
      - neo4j
    environment:
      RDS_DB_NAME: apixdb
      RDS_USERNAME: apix
      RDS_PASSWORD: 789789
      RDS_HOSTNAME: postgres
      VIRTUAL_HOST: apix.rocks
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: apix.rocks
      LETSENCRYPT_EMAIL: cliqqit@gmail.com
    networks:
      - proxy-tier

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: apix
      POSTGRES_DB: apixdb

  neo4j:
    image: neo4j:3.2
    environment:
      NEO4J_AUTH: none
      RDS_PORT: 5432

networks:
  proxy-tier:
    external:
      name: nginx-proxy
