version: "3"
services:
  web-test:
    build: .
    command: bash -c "./wait-for-it.sh neo4j-test:7474 -- gem install bundler; bundle install; rails db:migrate:reset; bundle exec rails t"
    volumes:
      - ./app:/app
    links:
      - neo4j-test
    external_links:
      - postgres
    environment:
      RDS_DB_NAME: apixdb
      RDS_USERNAME: apix
      RDS_PASSWORD: 789789
      RDS_HOSTNAME: postgres
      RDS_PORT: 5432
      RAILS_ENV: test

  neo4j-test:
    image: neo4j:3.4
    restart: unless-stopped
    environment:
      NEO4J_AUTH: none
